# Generated by Django 4.2.16 on 2025-06-23 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amenity_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="amenity_icons/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hotel_name", models.CharField(max_length=255)),
                ("hotel_description", models.TextField()),
                ("hotel_location", models.CharField(max_length=255)),
                ("hotel_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("hotel_slug", models.SlugField(max_length=255, unique=True)),
                (
                    "hotel_offer_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("amenities", models.ManyToManyField(to="accounts.amenity")),
            ],
        ),
        migrations.CreateModel(
            name="HotelVendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="vendor_profile_pictures/"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                (
                    "email_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("otp", models.CharField(blank=True, max_length=6, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "business_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotel_vendor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hotel_vendor",
            },
        ),
        migrations.CreateModel(
            name="HotelUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                (
                    "email_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("otp", models.CharField(blank=True, max_length=6, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotel_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hotel_user",
            },
        ),
        migrations.CreateModel(
            name="HotelManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manager_name", models.CharField(max_length=255)),
                (
                    "manager_contact",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.hotel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HotelImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="hotel_images/")),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotel_images",
                        to="accounts.hotel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="hotel",
            name="hotel_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.hotelvendor"
            ),
        ),
    ]
